name: Workflow dispatch
on:
  workflow_dispatch:
    branchs:
      - main
    paths:
      - 'changes/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: HEAD
          filters: |
            changes:
              - 'changes/**'

      - if: steps.changes.outputs.changes == 'true'
        run: echo changed

      - run: echo ${{ steps.changes.outputs.changes }}

      - run: cat $GITHUB_EVENT_PATH
