name: Workflow dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          base: ${{ github.ref }}
          filters: |
            changes:
              - 'changes/**'

      - if: steps.changed.outputs.changes == 'true'
        run: echo changed

      - run: cat $GITHUB_EVENT_PATH
